name: Generate Weekly PDFs

on:
  schedule:
    - cron: '0 */2 * * *'  # Every 2 hours
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt

      - name: Run PDF Generator Script
        env:
          SMARTSHEET_API_TOKEN: ${{ secrets.SMARTSHEET_API_TOKEN }}
          SOURCE_SHEET_ID: ${{ secrets.SOURCE_SHEET_ID }}
        run: python generate_weekly_pdfs.py

      - name: Commit and Push Generated PDFs and Metadata
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add docs/assets/*.pdf docs/assets/metadata.json
          git diff --cached --quiet || git commit -m "📄 Auto-update PDFs and metadata"
          git push https://x-access-token:${GH_PAT}@github.com/${{ github.repository }}.git HEAD:main
