name: Generate Weekly PDFs

on:
  schedule:
    - cron: '0 */2 * * *'  # Every 2 hours
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run PDF generator
        env:
          SMARTSHEET_API_TOKEN: ${{ secrets.SMARTSHEET_API_TOKEN }}
          SOURCE_SHEET_ID: ${{ secrets.SOURCE_SHEET_ID }}
        run: python generate_weekly_pdfs.py

      - name: Commit and push updated PDFs and metadata
        run: |
          git config user.name "JFlo21"
          git config user.email "floresj5400@gmail.com"
          git add docs/assets/*.pdf docs/assets/metadata.json
          git diff --cached --quiet || git commit -m "📄 Auto-update PDFs and metadata"
          git push https://x-access-token:${{ secrets.GH_PAT }}@github.com/JFlo21/Generate-Weekly-PDFs-DSR-Resiliency.git HEAD:main
